 http://localhost:8080/
###
POST http://localhost:8080/pathname?body=hola
###
POST http://localhost:8080/pathname?status=601
###
POST http://localhost:8080/pathname?headers={"x-hello":"world"}
###
GET https://mockup-api.deno.dev/?body={"a":1}&headers={"content-type":"application/json"}
